version: "3.8"
services:

  postgresql:
    image: postgres
    container_name: keycloak_postgres
    env_file:
      - .env
    command: "
                  postgres
                    -c max_connections=200
                    -c logging_collector=on
                    -c log_min_messages=LOG
                    -c log_directory=/var/log/postgresql"
    ports:
      - 5432:5432

  keycloak:
    image: quay.io/keycloak/keycloak:26.1.4
    container_name: keycloak
    ports:
      - "8008:8080"
    env_file:
      - .env
    command: [ "start-dev" ]